-- Seed all US universities as campuses
-- Run with: sudo -u postgres psql -d campuscuts -f seed_campuses.sql

-- First, delete invalid entries
DELETE FROM campuses WHERE name IN ('GMAIL', 'ICLOUD');

-- Insert all universities (ON CONFLICT DO NOTHING to avoid duplicates)
INSERT INTO campuses (id, slug, name, city, state, timezone, "updatedAt")
VALUES
  (gen_random_uuid(), 'abilene-christian', 'Abilene Christian University', 'Abilene', 'TX', 'America/Chicago', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'air-force', 'United States Air Force Academy', 'Colorado Springs', 'CO', 'America/Denver', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'akron', 'University of Akron', 'Akron', 'OH', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'alabama', 'University of Alabama', 'Tuscaloosa', 'AL', 'America/Chicago', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'alabama-birmingham', 'University of Alabama at Birmingham', 'Birmingham', 'AL', 'America/Chicago', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'alabama-huntsville', 'University of Alabama in Huntsville', 'Huntsville', 'AL', 'America/Chicago', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'alabama-state', 'Alabama State University', 'Montgomery', 'AL', 'America/Chicago', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'albany', 'University at Albany SUNY', 'Albany', 'NY', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'american', 'American University', 'Washington', 'DC', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'amherst', 'Amherst College', 'Amherst', 'MA', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'appalachian-state', 'Appalachian State University', 'Boone', 'NC', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'arizona', 'University of Arizona', 'Tucson', 'AZ', 'America/Phoenix', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'arizona-state', 'Arizona State University', 'Tempe', 'AZ', 'America/Phoenix', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'arkansas', 'University of Arkansas', 'Fayetteville', 'AR', 'America/Chicago', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'army', 'United States Military Academy', 'West Point', 'NY', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'auburn', 'Auburn University', 'Auburn', 'AL', 'America/Chicago', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'ball-state', 'Ball State University', 'Muncie', 'IN', 'America/Indiana/Indianapolis', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'baylor', 'Baylor University', 'Waco', 'TX', 'America/Chicago', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'binghamton', 'Binghamton University', 'Binghamton', 'NY', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'boise-state', 'Boise State University', 'Boise', 'ID', 'America/Boise', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'boston-college', 'Boston College', 'Chestnut Hill', 'MA', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'boston-university', 'Boston University', 'Boston', 'MA', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'bowling-green', 'Bowling Green State University', 'Bowling Green', 'OH', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'brandeis', 'Brandeis University', 'Waltham', 'MA', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'brigham-young', 'Brigham Young University', 'Provo', 'UT', 'America/Denver', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'brown', 'Brown University', 'Providence', 'RI', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'buffalo', 'University at Buffalo', 'Buffalo', 'NY', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'butler', 'Butler University', 'Indianapolis', 'IN', 'America/Indiana/Indianapolis', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'cal-poly-pomona', 'Cal Poly Pomona', 'Pomona', 'CA', 'America/Los_Angeles', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'cal-state-fullerton', 'CSU Fullerton', 'Fullerton', 'CA', 'America/Los_Angeles', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'cal-state-la', 'CSU Los Angeles', 'Los Angeles', 'CA', 'America/Los_Angeles', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'cal-state-long-beach', 'CSU Long Beach', 'Long Beach', 'CA', 'America/Los_Angeles', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'cal-state-northridge', 'CSU Northridge', 'Northridge', 'CA', 'America/Los_Angeles', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'caltech', 'California Institute of Technology', 'Pasadena', 'CA', 'America/Los_Angeles', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'carnegie-mellon', 'Carnegie Mellon University', 'Pittsburgh', 'PA', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'case-western', 'Case Western Reserve University', 'Cleveland', 'OH', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'central-florida', 'University of Central Florida', 'Orlando', 'FL', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'central-michigan', 'Central Michigan University', 'Mount Pleasant', 'MI', 'America/Detroit', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'charleston', 'College of Charleston', 'Charleston', 'SC', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'cincinnati', 'University of Cincinnati', 'Cincinnati', 'OH', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'clemson', 'Clemson University', 'Clemson', 'SC', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'coastal-carolina', 'Coastal Carolina University', 'Conway', 'SC', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'colorado', 'University of Colorado Boulder', 'Boulder', 'CO', 'America/Denver', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'colorado-state', 'Colorado State University', 'Fort Collins', 'CO', 'America/Denver', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'columbia', 'Columbia University', 'New York', 'NY', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'connecticut', 'University of Connecticut', 'Storrs', 'CT', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'cornell', 'Cornell University', 'Ithaca', 'NY', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'creighton', 'Creighton University', 'Omaha', 'NE', 'America/Chicago', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'dartmouth', 'Dartmouth College', 'Hanover', 'NH', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'dayton', 'University of Dayton', 'Dayton', 'OH', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'delaware', 'University of Delaware', 'Newark', 'DE', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'denver', 'University of Denver', 'Denver', 'CO', 'America/Denver', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'depaul', 'DePaul University', 'Chicago', 'IL', 'America/Chicago', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'drake', 'Drake University', 'Des Moines', 'IA', 'America/Chicago', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'drexel', 'Drexel University', 'Philadelphia', 'PA', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'duke', 'Duke University', 'Durham', 'NC', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'duquesne', 'Duquesne University', 'Pittsburgh', 'PA', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'east-carolina', 'East Carolina University', 'Greenville', 'NC', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'eastern-michigan', 'Eastern Michigan University', 'Ypsilanti', 'MI', 'America/Detroit', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'emory', 'Emory University', 'Atlanta', 'GA', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'fau', 'Florida Atlantic University', 'Boca Raton', 'FL', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'fiu', 'Florida International University', 'Miami', 'FL', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'florida', 'University of Florida', 'Gainesville', 'FL', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'florida-state', 'Florida State University', 'Tallahassee', 'FL', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'fordham', 'Fordham University', 'Bronx', 'NY', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'fresno-state', 'CSU Fresno', 'Fresno', 'CA', 'America/Los_Angeles', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'george-mason', 'George Mason University', 'Fairfax', 'VA', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'george-washington', 'George Washington University', 'Washington', 'DC', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'georgetown', 'Georgetown University', 'Washington', 'DC', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'georgia', 'University of Georgia', 'Athens', 'GA', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'georgia-southern', 'Georgia Southern University', 'Statesboro', 'GA', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'georgia-state', 'Georgia State University', 'Atlanta', 'GA', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'georgia-tech', 'Georgia Institute of Technology', 'Atlanta', 'GA', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'gonzaga', 'Gonzaga University', 'Spokane', 'WA', 'America/Los_Angeles', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'harvard', 'Harvard University', 'Cambridge', 'MA', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'hawaii', 'University of Hawaii at Manoa', 'Honolulu', 'HI', 'Pacific/Honolulu', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'hofstra', 'Hofstra University', 'Hempstead', 'NY', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'holy-cross', 'College of the Holy Cross', 'Worcester', 'MA', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'houston', 'University of Houston', 'Houston', 'TX', 'America/Chicago', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'howard', 'Howard University', 'Washington', 'DC', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'illinois', 'University of Illinois', 'Champaign', 'IL', 'America/Chicago', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'illinois-chicago', 'University of Illinois Chicago', 'Chicago', 'IL', 'America/Chicago', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'indiana', 'Indiana University', 'Bloomington', 'IN', 'America/Indiana/Indianapolis', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'iowa', 'University of Iowa', 'Iowa City', 'IA', 'America/Chicago', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'iowa-state', 'Iowa State University', 'Ames', 'IA', 'America/Chicago', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'james-madison', 'James Madison University', 'Harrisonburg', 'VA', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'johns-hopkins', 'Johns Hopkins University', 'Baltimore', 'MD', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'kansas', 'University of Kansas', 'Lawrence', 'KS', 'America/Chicago', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'kansas-state', 'Kansas State University', 'Manhattan', 'KS', 'America/Chicago', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'kent-state', 'Kent State University', 'Kent', 'OH', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'kentucky', 'University of Kentucky', 'Lexington', 'KY', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'lehigh', 'Lehigh University', 'Bethlehem', 'PA', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'liberty', 'Liberty University', 'Lynchburg', 'VA', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'louisiana-state', 'Louisiana State University', 'Baton Rouge', 'LA', 'America/Chicago', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'louisville', 'University of Louisville', 'Louisville', 'KY', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'loyola-chicago', 'Loyola University Chicago', 'Chicago', 'IL', 'America/Chicago', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'loyola-marymount', 'Loyola Marymount University', 'Los Angeles', 'CA', 'America/Los_Angeles', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'marquette', 'Marquette University', 'Milwaukee', 'WI', 'America/Chicago', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'maryland', 'University of Maryland', 'College Park', 'MD', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'massachusetts', 'UMass Amherst', 'Amherst', 'MA', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'memphis', 'University of Memphis', 'Memphis', 'TN', 'America/Chicago', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'miami', 'University of Miami', 'Coral Gables', 'FL', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'miami-ohio', 'Miami University', 'Oxford', 'OH', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'michigan', 'University of Michigan', 'Ann Arbor', 'MI', 'America/Detroit', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'michigan-state', 'Michigan State University', 'East Lansing', 'MI', 'America/Detroit', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'minnesota', 'University of Minnesota', 'Minneapolis', 'MN', 'America/Chicago', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'mississippi', 'University of Mississippi', 'Oxford', 'MS', 'America/Chicago', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'mississippi-state', 'Mississippi State University', 'Starkville', 'MS', 'America/Chicago', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'missouri', 'University of Missouri', 'Columbia', 'MO', 'America/Chicago', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'mit', 'Massachusetts Institute of Technology', 'Cambridge', 'MA', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'montana', 'University of Montana', 'Missoula', 'MT', 'America/Denver', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'navy', 'United States Naval Academy', 'Annapolis', 'MD', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'nebraska', 'University of Nebraska-Lincoln', 'Lincoln', 'NE', 'America/Chicago', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'nevada', 'University of Nevada Reno', 'Reno', 'NV', 'America/Los_Angeles', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'nevada-las-vegas', 'University of Nevada Las Vegas', 'Las Vegas', 'NV', 'America/Los_Angeles', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'new-hampshire', 'University of New Hampshire', 'Durham', 'NH', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'new-mexico', 'University of New Mexico', 'Albuquerque', 'NM', 'America/Denver', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'new-mexico-state', 'New Mexico State University', 'Las Cruces', 'NM', 'America/Denver', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'north-carolina', 'UNC Chapel Hill', 'Chapel Hill', 'NC', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'north-carolina-state', 'NC State University', 'Raleigh', 'NC', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'north-texas', 'University of North Texas', 'Denton', 'TX', 'America/Chicago', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'northeastern', 'Northeastern University', 'Boston', 'MA', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'northern-illinois', 'Northern Illinois University', 'DeKalb', 'IL', 'America/Chicago', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'northwestern', 'Northwestern University', 'Evanston', 'IL', 'America/Chicago', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'notre-dame', 'University of Notre Dame', 'Notre Dame', 'IN', 'America/Indiana/Indianapolis', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'ohio', 'Ohio University', 'Athens', 'OH', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'ohio-state', 'Ohio State University', 'Columbus', 'OH', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'oklahoma', 'University of Oklahoma', 'Norman', 'OK', 'America/Chicago', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'oklahoma-state', 'Oklahoma State University', 'Stillwater', 'OK', 'America/Chicago', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'old-dominion', 'Old Dominion University', 'Norfolk', 'VA', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'oregon', 'University of Oregon', 'Eugene', 'OR', 'America/Los_Angeles', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'oregon-state', 'Oregon State University', 'Corvallis', 'OR', 'America/Los_Angeles', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'penn', 'University of Pennsylvania', 'Philadelphia', 'PA', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'penn-state', 'Penn State University', 'University Park', 'PA', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'pepperdine', 'Pepperdine University', 'Malibu', 'CA', 'America/Los_Angeles', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'pittsburgh', 'University of Pittsburgh', 'Pittsburgh', 'PA', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'princeton', 'Princeton University', 'Princeton', 'NJ', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'providence', 'Providence College', 'Providence', 'RI', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'purdue', 'Purdue University', 'West Lafayette', 'IN', 'America/Indiana/Indianapolis', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'rice', 'Rice University', 'Houston', 'TX', 'America/Chicago', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'richmond', 'University of Richmond', 'Richmond', 'VA', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'rochester', 'University of Rochester', 'Rochester', 'NY', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'rutgers', 'Rutgers University', 'New Brunswick', 'NJ', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'saint-louis', 'Saint Louis University', 'St Louis', 'MO', 'America/Chicago', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'san-diego', 'University of San Diego', 'San Diego', 'CA', 'America/Los_Angeles', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'san-diego-state', 'San Diego State University', 'San Diego', 'CA', 'America/Los_Angeles', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'san-francisco', 'University of San Francisco', 'San Francisco', 'CA', 'America/Los_Angeles', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'san-jose-state', 'San Jose State University', 'San Jose', 'CA', 'America/Los_Angeles', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'santa-clara', 'Santa Clara University', 'Santa Clara', 'CA', 'America/Los_Angeles', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'seton-hall', 'Seton Hall University', 'South Orange', 'NJ', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'smu', 'Southern Methodist University', 'Dallas', 'TX', 'America/Chicago', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'south-carolina', 'University of South Carolina', 'Columbia', 'SC', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'south-florida', 'University of South Florida', 'Tampa', 'FL', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'southern-california', 'University of Southern California', 'Los Angeles', 'CA', 'America/Los_Angeles', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'stanford', 'Stanford University', 'Stanford', 'CA', 'America/Los_Angeles', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'stony-brook', 'Stony Brook University', 'Stony Brook', 'NY', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'syracuse', 'Syracuse University', 'Syracuse', 'NY', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'tcu', 'Texas Christian University', 'Fort Worth', 'TX', 'America/Chicago', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'temple', 'Temple University', 'Philadelphia', 'PA', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'tennessee', 'University of Tennessee', 'Knoxville', 'TN', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'texas', 'University of Texas at Austin', 'Austin', 'TX', 'America/Chicago', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'texas-am', 'Texas A&M University', 'College Station', 'TX', 'America/Chicago', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'texas-state', 'Texas State University', 'San Marcos', 'TX', 'America/Chicago', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'texas-tech', 'Texas Tech University', 'Lubbock', 'TX', 'America/Chicago', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'toledo', 'University of Toledo', 'Toledo', 'OH', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'towson', 'Towson University', 'Towson', 'MD', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'tulane', 'Tulane University', 'New Orleans', 'LA', 'America/Chicago', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'tulsa', 'University of Tulsa', 'Tulsa', 'OK', 'America/Chicago', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'uc-berkeley', 'UC Berkeley', 'Berkeley', 'CA', 'America/Los_Angeles', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'uc-davis', 'UC Davis', 'Davis', 'CA', 'America/Los_Angeles', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'uc-irvine', 'UC Irvine', 'Irvine', 'CA', 'America/Los_Angeles', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'ucla', 'UCLA', 'Los Angeles', 'CA', 'America/Los_Angeles', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'uc-riverside', 'UC Riverside', 'Riverside', 'CA', 'America/Los_Angeles', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'uc-san-diego', 'UC San Diego', 'La Jolla', 'CA', 'America/Los_Angeles', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'uc-santa-barbara', 'UC Santa Barbara', 'Santa Barbara', 'CA', 'America/Los_Angeles', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'uc-santa-cruz', 'UC Santa Cruz', 'Santa Cruz', 'CA', 'America/Los_Angeles', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'utah', 'University of Utah', 'Salt Lake City', 'UT', 'America/Denver', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'utah-state', 'Utah State University', 'Logan', 'UT', 'America/Denver', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'vanderbilt', 'Vanderbilt University', 'Nashville', 'TN', 'America/Chicago', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'vermont', 'University of Vermont', 'Burlington', 'VT', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'villanova', 'Villanova University', 'Villanova', 'PA', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'virginia', 'University of Virginia', 'Charlottesville', 'VA', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'virginia-tech', 'Virginia Tech', 'Blacksburg', 'VA', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'wake-forest', 'Wake Forest University', 'Winston-Salem', 'NC', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'washington', 'University of Washington', 'Seattle', 'WA', 'America/Los_Angeles', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'washington-state', 'Washington State University', 'Pullman', 'WA', 'America/Los_Angeles', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'west-virginia', 'West Virginia University', 'Morgantown', 'WV', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'western-michigan', 'Western Michigan University', 'Kalamazoo', 'MI', 'America/Detroit', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'wichita-state', 'Wichita State University', 'Wichita', 'KS', 'America/Chicago', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'william-mary', 'William and Mary', 'Williamsburg', 'VA', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'wisconsin', 'University of Wisconsin-Madison', 'Madison', 'WI', 'America/Chicago', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'wyoming', 'University of Wyoming', 'Laramie', 'WY', 'America/Denver', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'xavier', 'Xavier University', 'Cincinnati', 'OH', 'America/New_York', CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'yale', 'Yale University', 'New Haven', 'CT', 'America/New_York', CURRENT_TIMESTAMP)
ON CONFLICT (slug) DO NOTHING;

-- Show count of campuses
SELECT COUNT(*) as total_campuses FROM campuses;

