-- AI Worker Database Schema
-- This schema stores AI-generated insights, scores, and recommendations

-- Barber quality scores generated by AI
CREATE TABLE IF NOT EXISTS barber_quality_scores (
  id SERIAL PRIMARY KEY,
  barber_id VARCHAR(255) NOT NULL,
  quality_score NUMERIC(5,2) NOT NULL CHECK (quality_score >= 0 AND quality_score <= 100),
  sentiment_score NUMERIC(3,2) CHECK (sentiment_score >= -1 AND sentiment_score <= 1),
  reasoning TEXT NOT NULL,
  factors JSONB,
  created_at TIMESTAMP DEFAULT NOW(),
  CONSTRAINT fk_barber FOREIGN KEY (barber_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_barber_quality_scores_barber_id ON barber_quality_scores(barber_id);
CREATE INDEX idx_barber_quality_scores_created_at ON barber_quality_scores(created_at DESC);

-- Dynamic pricing multipliers
CREATE TABLE IF NOT EXISTS barber_pricing_multipliers (
  id SERIAL PRIMARY KEY,
  barber_id VARCHAR(255) NOT NULL,
  multiplier NUMERIC(3,2) NOT NULL CHECK (multiplier >= 0.8 AND multiplier <= 1.5),
  base_multiplier NUMERIC(3,2),
  campus_coefficient NUMERIC(3,2),
  demand_factor NUMERIC(3,2),
  quality_factor NUMERIC(3,2),
  reasoning TEXT,
  expires_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW(),
  CONSTRAINT fk_barber_pricing FOREIGN KEY (barber_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_pricing_multipliers_barber_id ON barber_pricing_multipliers(barber_id);
CREATE INDEX idx_pricing_multipliers_expires_at ON barber_pricing_multipliers(expires_at);

-- AI events log for all processing activities
CREATE TABLE IF NOT EXISTS ai_events_log (
  id SERIAL PRIMARY KEY,
  event_type VARCHAR(100) NOT NULL,
  event_data JSONB NOT NULL,
  processing_time_ms INTEGER,
  status VARCHAR(50) NOT NULL,
  error_message TEXT,
  ai_model VARCHAR(100),
  tokens_used INTEGER,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_ai_events_log_event_type ON ai_events_log(event_type);
CREATE INDEX idx_ai_events_log_created_at ON ai_events_log(created_at DESC);
CREATE INDEX idx_ai_events_log_status ON ai_events_log(status);

-- Fraud detection flags
CREATE TABLE IF NOT EXISTS fraud_flags (
  id SERIAL PRIMARY KEY,
  user_id VARCHAR(255) NOT NULL,
  risk_score NUMERIC(5,2) NOT NULL CHECK (risk_score >= 0 AND risk_score <= 100),
  risk_level VARCHAR(20) NOT NULL CHECK (risk_level IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
  fraud_indicators JSONB NOT NULL,
  pattern_type VARCHAR(100),
  confidence NUMERIC(3,2) CHECK (confidence >= 0 AND confidence <= 1),
  recommended_action TEXT,
  status VARCHAR(50) DEFAULT 'PENDING',
  reviewed_by VARCHAR(255),
  reviewed_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW(),
  CONSTRAINT fk_user_fraud FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_fraud_flags_user_id ON fraud_flags(user_id);
CREATE INDEX idx_fraud_flags_risk_level ON fraud_flags(risk_level);
CREATE INDEX idx_fraud_flags_status ON fraud_flags(status);
CREATE INDEX idx_fraud_flags_created_at ON fraud_flags(created_at DESC);

-- Dispute resolution recommendations
CREATE TABLE IF NOT EXISTS dispute_recommendations (
  id SERIAL PRIMARY KEY,
  booking_id VARCHAR(255) NOT NULL,
  barber_id VARCHAR(255) NOT NULL,
  customer_id VARCHAR(255) NOT NULL,
  at_fault VARCHAR(50) CHECK (at_fault IN ('barber', 'customer', 'unclear', 'none')),
  confidence NUMERIC(3,2) CHECK (confidence >= 0 AND confidence <= 1),
  recommended_action VARCHAR(100) CHECK (recommended_action IN ('refund', 'partial_refund', 'deny', 'mediate', 'escalate')),
  refund_percentage NUMERIC(5,2),
  reasoning TEXT NOT NULL,
  evidence_analyzed JSONB,
  admin_decision VARCHAR(100),
  admin_notes TEXT,
  resolved_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_dispute_recommendations_booking_id ON dispute_recommendations(booking_id);
CREATE INDEX idx_dispute_recommendations_created_at ON dispute_recommendations(created_at DESC);

-- Market demand statistics
CREATE TABLE IF NOT EXISTS market_stats (
  id SERIAL PRIMARY KEY,
  campus_id VARCHAR(255) NOT NULL,
  demand_index NUMERIC(3,2) NOT NULL CHECK (demand_index >= 0 AND demand_index <= 2),
  active_barbers INTEGER NOT NULL,
  active_customers INTEGER NOT NULL,
  avg_wait_time_hours NUMERIC(5,2),
  booking_velocity NUMERIC(5,2),
  supply_demand_ratio NUMERIC(5,2),
  trending_services JSONB,
  peak_hours JSONB,
  insights TEXT,
  week_start DATE NOT NULL,
  week_end DATE NOT NULL,
  created_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(campus_id, week_start)
);

CREATE INDEX idx_market_stats_campus_id ON market_stats(campus_id);
CREATE INDEX idx_market_stats_week_start ON market_stats(week_start DESC);

-- Barber behavior metrics (for AI analysis)
CREATE TABLE IF NOT EXISTS barber_behavior_metrics (
  id SERIAL PRIMARY KEY,
  barber_id VARCHAR(255) NOT NULL,
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  total_bookings INTEGER DEFAULT 0,
  completed_bookings INTEGER DEFAULT 0,
  cancelled_bookings INTEGER DEFAULT 0,
  late_arrivals INTEGER DEFAULT 0,
  repeat_customers INTEGER DEFAULT 0,
  avg_rating NUMERIC(3,2),
  review_count INTEGER DEFAULT 0,
  response_time_minutes NUMERIC(8,2),
  cancellation_rate NUMERIC(5,4),
  lateness_rate NUMERIC(5,4),
  repeat_rate NUMERIC(5,4),
  revenue_generated NUMERIC(10,2),
  created_at TIMESTAMP DEFAULT NOW(),
  CONSTRAINT fk_barber_metrics FOREIGN KEY (barber_id) REFERENCES users(id) ON DELETE CASCADE,
  UNIQUE(barber_id, period_start, period_end)
);

CREATE INDEX idx_barber_behavior_metrics_barber_id ON barber_behavior_metrics(barber_id);
CREATE INDEX idx_barber_behavior_metrics_period ON barber_behavior_metrics(period_start DESC);

-- Weekly admin summaries
CREATE TABLE IF NOT EXISTS weekly_admin_summaries (
  id SERIAL PRIMARY KEY,
  week_start DATE NOT NULL,
  week_end DATE NOT NULL,
  total_revenue NUMERIC(12,2),
  total_bookings INTEGER,
  new_users INTEGER,
  fraud_alerts INTEGER,
  dispute_count INTEGER,
  top_performing_barbers JSONB,
  underperforming_barbers JSONB,
  market_trends JSONB,
  pricing_changes JSONB,
  anomalies JSONB,
  recommendations TEXT,
  email_sent BOOLEAN DEFAULT FALSE,
  email_sent_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(week_start)
);

CREATE INDEX idx_weekly_summaries_week_start ON weekly_admin_summaries(week_start DESC);

-- Onboarding assessments
CREATE TABLE IF NOT EXISTS onboarding_assessments (
  id SERIAL PRIMARY KEY,
  user_id VARCHAR(255) NOT NULL,
  user_type VARCHAR(50) NOT NULL,
  risk_assessment JSONB,
  quality_prediction NUMERIC(5,2),
  success_likelihood NUMERIC(3,2) CHECK (success_likelihood >= 0 AND success_likelihood <= 1),
  recommendations TEXT,
  flags JSONB,
  approved BOOLEAN,
  approved_by VARCHAR(255),
  approved_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW(),
  CONSTRAINT fk_user_onboarding FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_onboarding_assessments_user_id ON onboarding_assessments(user_id);
CREATE INDEX idx_onboarding_assessments_created_at ON onboarding_assessments(created_at DESC);

