/**
 * Campus Manager Dashboard
 * 
 * Conditional overlay shown only when barber.isCampusManager === true
 * Reuses 100% of existing Barber page styles and layout
 */

import React, { useState, useEffect } from 'react';
import { 
  Users, 
  TrendingUp, 
  FileText, 
  AlertTriangle,
  CheckCircle,
  XCircle,
  Clock,
  Calendar,
  Flag,
  RefreshCw
} from 'lucide-react';
import Card from './Card';
import Button from './Button';
import { CampusManagerBarberView } from './CampusManagerBarberView';
import barberApplicationService, { BarberApplication } from '../services/barber-application.service';
import toast from 'react-hot-toast';

interface Incident {
  id: string;
  barberName: string;
  type: string;
  description: string;
  status: 'open' | 'escalated' | 'resolved';
  createdAt: Date;
}

// Automated review aggregation interfaces
interface NegativeReview {
  reviewId: string;
  customerName: string;
  rating: number;
  comment: string;
  createdAt: Date;
  sentiment: 'negative' | 'very_negative';
  analysis: string;
}

interface AutoGeneratedIncident {
  id: string;
  barberId: string;
  barberName: string;
  barberEmail: string;
  type: 'quality' | 'professionalism' | 'safety' | 'other';
  severity: 'low' | 'medium' | 'high' | 'critical';
  negativeReviewCount: number;
  negativeReviews: NegativeReview[];
  summary: string;
  recommendation: string;
  detectedAt: Date;
  status: 'pending_review' | 'acknowledged' | 'escalated' | 'resolved';
  campusManagerNotes?: string;
}

interface CampusManagerDashboardProps {
  campusId: string;
  campusName: string;
}

// ═══════════════════════════════════════════════════════════════
// INCIDENT DETAILS MODAL
// ═══════════════════════════════════════════════════════════════

const IncidentDetailsModal: React.FC<{ 
  incident: AutoGeneratedIncident; 
  onClose: () => void 
}> = ({ incident, onClose }) => {
  return (
    <div 
      className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-[60] p-2 sm:p-4"
      onClick={onClose}
    >
      <div 
        className="bg-white rounded-lg shadow-xl max-w-4xl w-full max-h-[95vh] sm:max-h-[90vh] overflow-y-auto"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="sticky top-0 bg-white border-b border-gray-200 px-4 sm:px-6 py-3 sm:py-4 flex items-center justify-between z-10">
          <div>
            <h2 className="text-base sm:text-xl font-bold text-gray-900">Incident Report Details</h2>
            <p className="text-xs sm:text-sm text-gray-500">Automatically generated from review patterns</p>
          </div>
          <button
            onClick={onClose}
            className="text-gray-400 hover:text-gray-600 text-2xl leading-none p-1"
          >
            ×
          </button>
        </div>

        {/* Content */}
        <div className="p-4 sm:p-6 space-y-4 sm:space-y-6">
          {/* Barber Info */}
          <Card className="p-4 sm:p-6">
            <h3 className="font-semibold text-gray-900 mb-3 sm:mb-4 text-sm sm:text-base">Barber Information</h3>
            <div className="grid grid-cols-2 gap-3 sm:gap-4 text-xs sm:text-sm">
              <div>
                <p className="text-gray-600">Name</p>
                <p className="font-medium text-gray-900">{incident.barberName}</p>
              </div>
              <div>
                <p className="text-gray-600">Email</p>
                <p className="font-medium text-gray-900 truncate">{incident.barberEmail}</p>
              </div>
              <div>
                <p className="text-gray-600">Issue Type</p>
                <p className="font-medium text-gray-900 capitalize">{incident.type}</p>
              </div>
              <div>
                <p className="text-gray-600">Severity</p>
                <p className="font-medium text-gray-900 capitalize">{incident.severity}</p>
              </div>
              <div>
                <p className="text-gray-600">Negative Reviews</p>
                <p className="font-medium text-gray-900">{incident.negativeReviewCount}</p>
              </div>
              <div>
                <p className="text-gray-600">Detected</p>
                <p className="font-medium text-gray-900">{incident.detectedAt.toLocaleDateString()}</p>
              </div>
            </div>
          </Card>

          {/* Pattern Analysis */}
          <Card className="p-4 sm:p-6 bg-blue-50 border-blue-200">
            <h3 className="font-semibold text-blue-900 mb-2 sm:mb-3 flex items-center gap-2 text-sm sm:text-base">
              <TrendingUp className="w-4 h-4 sm:w-5 sm:h-5" />
              Pattern Analysis
            </h3>
            <p className="text-xs sm:text-sm text-blue-800 leading-relaxed">{incident.summary}</p>
          </Card>

          {/* Recommendations */}
          <Card className="p-4 sm:p-6 bg-green-50 border-green-200">
            <h3 className="font-semibold text-green-900 mb-2 sm:mb-3 text-sm sm:text-base">Recommended Actions</h3>
            <p className="text-xs sm:text-sm text-green-800 leading-relaxed">{incident.recommendation}</p>
          </Card>

          {/* Individual Reviews */}
          <div>
            <h3 className="font-semibold text-gray-900 mb-3 sm:mb-4 text-sm sm:text-base">Negative Reviews ({incident.negativeReviews.length})</h3>
            <div className="space-y-3 sm:space-y-4">
              {incident.negativeReviews.map((review) => (
                <Card 
                  key={review.reviewId} 
                  className={`p-3 sm:p-5 ${
                    review.sentiment === 'very_negative' 
                      ? 'border-2 border-red-300 bg-red-50' 
                      : 'border border-gray-200'
                  }`}
                >
                  <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between mb-2 sm:mb-3 gap-2">
                    <div className="flex-1">
                      <div className="flex flex-wrap items-center gap-2 mb-1.5 sm:mb-2">
                        <span className="font-medium text-gray-900 text-sm sm:text-base">{review.customerName}</span>
                        <span className={`text-[10px] sm:text-xs font-bold px-1.5 sm:px-2 py-0.5 sm:py-1 rounded-full ${
                          review.sentiment === 'very_negative'
                            ? 'bg-red-100 text-red-700'
                            : 'bg-yellow-100 text-yellow-700'
                        }`}>
                          {review.sentiment.replace('_', ' ').toUpperCase()}
                        </span>
                      </div>
                      <div className="flex items-center gap-1 mb-1.5 sm:mb-2">
                        {[...Array(5)].map((_, i) => (
                          <span
                            key={i}
                            className={`text-sm sm:text-base ${i < review.rating ? 'text-yellow-400' : 'text-gray-300'}`}
                          >
                            ★
                          </span>
                        ))}
                        <span className="text-xs sm:text-sm text-gray-600 ml-2">
                          {review.createdAt.toLocaleDateString()}
                        </span>
                      </div>
                    </div>
                  </div>
                  
                  <div className="mb-2 sm:mb-3">
                    <p className="text-xs sm:text-sm text-gray-700 italic">"{review.comment}"</p>
                  </div>

                  <div className="p-2 sm:p-3 bg-white rounded-lg border border-gray-200">
                    <p className="text-[10px] sm:text-xs font-semibold text-gray-700 mb-0.5 sm:mb-1">Analysis:</p>
                    <p className="text-[10px] sm:text-xs text-gray-600">{review.analysis}</p>
                  </div>
                </Card>
              ))}
            </div>
          </div>

          {/* Actions */}
          <div className="flex flex-col sm:flex-row gap-2 sm:gap-3 sm:justify-end pt-4 border-t border-gray-200">
            <Button variant="outline" onClick={onClose} className="text-sm sm:text-base order-2 sm:order-1">
              Close
            </Button>
            <Button variant="primary" className="text-sm sm:text-base order-1 sm:order-2">
              <AlertTriangle className="w-4 h-4 mr-2" />
              Escalate to Admin
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
};

export const CampusManagerDashboard: React.FC<CampusManagerDashboardProps> = ({ 
  campusId, 
  campusName 
}) => {
  const [activeTab, setActiveTab] = useState<'applications' | 'barbers' | 'content' | 'incidents'>('applications');
  const [isTransitioning, setIsTransitioning] = useState(false);
  const [displayedTab, setDisplayedTab] = useState(activeTab);

  const handleTabChange = (newTab: typeof activeTab) => {
    if (newTab === activeTab) return;
    setIsTransitioning(true);
    setTimeout(() => {
      setDisplayedTab(newTab);
      setActiveTab(newTab);
      setTimeout(() => {
        setIsTransitioning(false);
      }, 20);
    }, 150);
  };

  return (
    <div className="space-y-4 sm:space-y-6">
      {/* Tab Navigation - Scrollable on mobile */}
      <div className="border-b border-gray-200 -mx-4 sm:mx-0 px-4 sm:px-0">
        <nav className="flex gap-1 sm:gap-6 overflow-x-auto pb-px scrollbar-hide">
          <button
            onClick={() => handleTabChange('applications')}
            className={`py-3 sm:py-4 px-3 sm:px-2 border-b-2 font-medium text-xs sm:text-sm transition-all duration-200 whitespace-nowrap flex-shrink-0 ${
              activeTab === 'applications'
                ? 'border-primary-500 text-primary-600'
                : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
            }`}
          >
            <div className="flex items-center gap-1.5 sm:gap-2">
              <Users className="w-4 h-4" />
              <span className="hidden sm:inline">Barber </span>Applications
            </div>
          </button>
          
          <button
            onClick={() => handleTabChange('barbers')}
            className={`py-3 sm:py-4 px-3 sm:px-2 border-b-2 font-medium text-xs sm:text-sm transition-all duration-200 whitespace-nowrap flex-shrink-0 ${
              activeTab === 'barbers'
                ? 'border-primary-500 text-primary-600'
                : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
            }`}
          >
            <div className="flex items-center gap-1.5 sm:gap-2">
              <Users className="w-4 h-4" />
              <span className="hidden sm:inline">Barber </span>Management
            </div>
          </button>
          
          <button
            onClick={() => handleTabChange('content')}
            className={`py-3 sm:py-4 px-3 sm:px-2 border-b-2 font-medium text-xs sm:text-sm transition-all duration-200 whitespace-nowrap flex-shrink-0 ${
              activeTab === 'content'
                ? 'border-primary-500 text-primary-600'
                : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
            }`}
          >
            <div className="flex items-center gap-1.5 sm:gap-2">
              <FileText className="w-4 h-4" />
              Content
            </div>
          </button>
          
          <button
            onClick={() => handleTabChange('incidents')}
            className={`py-3 sm:py-4 px-3 sm:px-2 border-b-2 font-medium text-xs sm:text-sm transition-all duration-200 whitespace-nowrap flex-shrink-0 ${
              activeTab === 'incidents'
                ? 'border-primary-500 text-primary-600'
                : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
            }`}
          >
            <div className="flex items-center gap-1.5 sm:gap-2">
              <AlertTriangle className="w-4 h-4" />
              Incidents
            </div>
          </button>
        </nav>
      </div>

      {/* Tab Content with smooth transition */}
      <div 
        className={`transition-all duration-150 ease-out ${
          isTransitioning 
            ? 'opacity-0 translate-y-2' 
            : 'opacity-100 translate-y-0'
        }`}
      >
        {displayedTab === 'applications' && <BarberApplicationsPanel campusId={campusId} />}
        {displayedTab === 'barbers' && <BarberManagementPanel campusId={campusId} campusName={campusName} />}
        {displayedTab === 'content' && <ContentManagementPanel campusId={campusId} />}
        {displayedTab === 'incidents' && <IncidentsPanel campusId={campusId} />}
      </div>
    </div>
  );
};

// ═══════════════════════════════════════════════════════════════
// BARBER APPLICATIONS PANEL
// ═══════════════════════════════════════════════════════════════

const BarberApplicationsPanel: React.FC<{ campusId: string }> = ({ campusId }) => {
  const [applications, setApplications] = useState<BarberApplication[]>([]);
  const [loading, setLoading] = useState(true);
  const [actionLoading, setActionLoading] = useState<string | null>(null);

  const fetchApplications = async () => {
    try {
      setLoading(true);
      const applications = await barberApplicationService.getAllApplications();
      setApplications(applications);
    } catch (error) {
      console.error('Failed to fetch applications:', error);
      toast.error('Failed to load barber applications');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchApplications();
  }, []);

  const handleAction = async (applicationId: string, action: 'approve' | 'reject' | 'interview') => {
    try {
      setActionLoading(applicationId);
      const statusMap = {
        'approve': 'approved' as const,
        'reject': 'rejected' as const,
        'interview': 'interview_scheduled' as const,
      };
      
      await barberApplicationService.updateApplicationStatus(applicationId, statusMap[action]);
      toast.success(`Application ${action === 'interview' ? 'scheduled for interview' : action + 'd'} successfully`);
      fetchApplications(); // Refresh the list
    } catch (error) {
      console.error(`Failed to ${action} application:`, error);
      toast.error(`Failed to ${action} application`);
    } finally {
      setActionLoading(null);
    }
  };

  const getStatusStyle = (status: string) => {
    switch (status) {
      case 'pending': return 'bg-yellow-100 text-yellow-700';
      case 'under_review': return 'bg-blue-100 text-blue-700';
      case 'interview_scheduled': return 'bg-purple-100 text-purple-700';
      case 'approved': return 'bg-green-100 text-green-700';
      case 'rejected': return 'bg-red-100 text-red-700';
      default: return 'bg-gray-100 text-gray-700';
    }
  };

  const formatStatus = (status: string) => {
    return status.split('_').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(' ');
  };

  if (loading) {
    return (
      <div className="space-y-4">
        <div className="flex items-center justify-between">
          <h3 className="text-base sm:text-lg font-semibold text-gray-900">Barber Applications</h3>
        </div>
        <Card className="text-center py-8 sm:py-12">
          <RefreshCw className="w-8 h-8 text-gray-400 mx-auto mb-3 animate-spin" />
          <p className="text-gray-500 text-sm sm:text-base">Loading applications...</p>
        </Card>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <h3 className="text-base sm:text-lg font-semibold text-gray-900">Barber Applications</h3>
        <div className="flex items-center gap-2">
          <span className="text-xs sm:text-sm text-gray-500">{applications.length} total</span>
          <button 
            onClick={fetchApplications}
            className="p-1.5 hover:bg-gray-100 rounded-lg transition-colors"
            title="Refresh"
          >
            <RefreshCw className="w-4 h-4 text-gray-500" />
          </button>
        </div>
      </div>

      {applications.length === 0 ? (
        <Card className="text-center py-8 sm:py-12">
          <Users className="w-10 h-10 sm:w-12 sm:h-12 text-gray-300 mx-auto mb-3 sm:mb-4" />
          <p className="text-gray-500 text-sm sm:text-base">No barber applications yet</p>
        </Card>
      ) : (
        <div className="space-y-3">
          {applications.map((app) => (
            <Card key={app.id} className="p-3 sm:p-4">
              <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-3">
                <div className="flex-1">
                  <h4 className="font-semibold text-gray-900 text-base sm:text-lg">
                    {app.first_name || app.user?.first_name || 'Unknown'} {app.last_name || app.user?.last_name || 'User'}
                  </h4>
                  <p className="text-sm text-gray-600 mt-1">{app.email || app.user?.email || 'No email'}</p>
                  <div className="flex flex-wrap items-center gap-2 sm:gap-4 mt-2">
                    <span className="text-xs text-gray-500">
                      Applied {new Date(app.created_at).toLocaleDateString()}
                    </span>
                    <span className={`text-xs font-medium px-2 py-1 rounded-full ${getStatusStyle(app.status)}`}>
                      {formatStatus(app.status)}
                    </span>
                    {app.years_experience && (
                      <span className="text-xs text-gray-500">
                        {app.years_experience} years exp.
                      </span>
                    )}
                  </div>
                  {app.why_be_barber && (
                    <p className="text-xs text-gray-600 mt-2 line-clamp-2">
                      "{app.why_be_barber}"
                    </p>
                  )}
                </div>
                
                {/* Buttons - Grid on mobile, flex on desktop */}
                <div className="grid grid-cols-2 sm:flex gap-2 sm:ml-4">
                  {app.status === 'pending' && (
                    <>
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => handleAction(app.id, 'interview')}
                        disabled={actionLoading === app.id}
                        className="text-xs sm:text-sm"
                      >
                        <Calendar className="w-3.5 h-3.5 sm:w-4 sm:h-4 mr-1" />
                        Interview
                      </Button>
                      <Button
                        variant="primary"
                        size="sm"
                        onClick={() => handleAction(app.id, 'approve')}
                        disabled={actionLoading === app.id}
                        className="text-xs sm:text-sm"
                      >
                        <CheckCircle className="w-3.5 h-3.5 sm:w-4 sm:h-4 mr-1" />
                        Approve
                      </Button>
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => handleAction(app.id, 'reject')}
                        disabled={actionLoading === app.id}
                        className="text-red-600 border-red-300 hover:bg-red-50 text-xs sm:text-sm col-span-2 sm:col-span-1"
                      >
                        <XCircle className="w-3.5 h-3.5 sm:w-4 sm:h-4 mr-1" />
                        Reject
                      </Button>
                    </>
                  )}
                  {(app.status === 'under_review' || app.status === 'interview_scheduled') && (
                    <>
                      <Button
                        variant="primary"
                        size="sm"
                        onClick={() => handleAction(app.id, 'approve')}
                        disabled={actionLoading === app.id}
                        className="text-xs sm:text-sm"
                      >
                        <CheckCircle className="w-3.5 h-3.5 sm:w-4 sm:h-4 mr-1" />
                        Approve
                      </Button>
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => handleAction(app.id, 'reject')}
                        disabled={actionLoading === app.id}
                        className="text-red-600 border-red-300 hover:bg-red-50 text-xs sm:text-sm"
                      >
                        <XCircle className="w-3.5 h-3.5 sm:w-4 sm:h-4 mr-1" />
                        Reject
                      </Button>
                    </>
                  )}
                  {app.status === 'approved' && (
                    <span className="text-xs text-green-600 font-medium flex items-center gap-1">
                      <CheckCircle className="w-4 h-4" />
                      Approved
                    </span>
                  )}
                  {app.status === 'rejected' && (
                    <span className="text-xs text-red-600 font-medium flex items-center gap-1">
                      <XCircle className="w-4 h-4" />
                      Rejected
                    </span>
                  )}
                </div>
              </div>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
};

// ═══════════════════════════════════════════════════════════════
// BARBER MANAGEMENT PANEL
// ═══════════════════════════════════════════════════════════════

interface CampusBarber {
  id: string;
  name: string;
  email: string;
  instagramHandle?: string;
  avgRating: number;
  totalBookings: number;
  completedBookings: number;
  isActive: boolean;
}

const BarberManagementPanel: React.FC<{ campusId: string; campusName: string }> = ({ campusId, campusName }) => {
  const [barbers, setBarbers] = useState<CampusBarber[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState('');
  const [filterStatus, setFilterStatus] = useState<'all' | 'active' | 'inactive'>('all');
  const [selectedBarberId, setSelectedBarberId] = useState<string | null>(null);

  const fetchBarbers = async () => {
    try {
      setLoading(true);
      const barberServiceModule = await import('../services/barber.service');
      const barberService = barberServiceModule.default;
      const response = await barberService.getBarbers({});
      
      // Extract barbers array from response - handle both paginated and direct array responses
      const barbersArray = Array.isArray(response) ? response : (response?.data || []);
      
      // Map API response to CampusBarber format
      const mappedBarbers: CampusBarber[] = barbersArray.map((barber: any) => ({
        id: barber.id,
        name: barber.name || barber.display_name || `${barber.first_name || ''} ${barber.last_name || ''}`.trim() || 'Unknown',
        email: barber.email || barber.user?.email || '',
        instagramHandle: barber.instagram_handle,
        avgRating: barber.average_rating || 0,
        totalBookings: barber.total_bookings || 0,
        completedBookings: barber.completed_bookings || barber.total_bookings || 0,
        isActive: barber.is_active !== false,
      }));
      
      setBarbers(mappedBarbers);
    } catch (error) {
      console.error('Failed to fetch barbers:', error);
      toast.error('Failed to load barbers');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchBarbers();
  }, [campusId]);

  // Filter barbers based on search and status
  const filteredBarbers = barbers.filter((barber) => {
    const matchesSearch = barber.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
                         barber.email.toLowerCase().includes(searchQuery.toLowerCase());
    const matchesStatus = filterStatus === 'all' || 
                         (filterStatus === 'active' && barber.isActive) ||
                         (filterStatus === 'inactive' && !barber.isActive);
    return matchesSearch && matchesStatus;
  });

  if (loading) {
    return (
      <div className="space-y-4">
        <div>
          <h3 className="text-base sm:text-lg font-semibold text-gray-900 mb-1">Barber Management</h3>
          <p className="text-xs sm:text-sm text-gray-500">View and manage barbers working on your campus</p>
        </div>
        <Card className="text-center py-8 sm:py-12">
          <RefreshCw className="w-8 h-8 text-gray-400 mx-auto mb-3 animate-spin" />
          <p className="text-gray-500 text-sm sm:text-base">Loading barbers...</p>
        </Card>
      </div>
    );
  }

  return (
    <div className="space-y-4 sm:space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h3 className="text-base sm:text-lg font-semibold text-gray-900 mb-1">Barber Management</h3>
          <p className="text-xs sm:text-sm text-gray-500">View and manage barbers working on your campus</p>
        </div>
        <button 
          onClick={fetchBarbers}
          className="p-1.5 hover:bg-gray-100 rounded-lg transition-colors"
          title="Refresh"
        >
          <RefreshCw className="w-4 h-4 text-gray-500" />
        </button>
      </div>

      {/* Search and Filter */}
      <div className="flex flex-col gap-3 sm:gap-4">
        <div className="flex-1 relative">
          <input
            type="text"
            placeholder="Search by name or email..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full pl-4 pr-4 py-2.5 sm:py-2 text-sm border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-400 focus:border-transparent"
          />
        </div>
        <div className="flex gap-2 overflow-x-auto pb-1 scrollbar-hide">
          <button
            onClick={() => setFilterStatus('all')}
            className={`px-3 sm:px-4 py-2 rounded-lg font-medium text-xs sm:text-sm transition-colors whitespace-nowrap flex-shrink-0 ${
              filterStatus === 'all'
                ? 'bg-primary-500 text-white'
                : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
            }`}
          >
            All ({barbers.length})
          </button>
          <button
            onClick={() => setFilterStatus('active')}
            className={`px-3 sm:px-4 py-2 rounded-lg font-medium text-xs sm:text-sm transition-colors whitespace-nowrap flex-shrink-0 ${
              filterStatus === 'active'
                ? 'bg-primary-500 text-white'
                : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
            }`}
          >
            Active ({barbers.filter(b => b.isActive).length})
          </button>
          <button
            onClick={() => setFilterStatus('inactive')}
            className={`px-3 sm:px-4 py-2 rounded-lg font-medium text-xs sm:text-sm transition-colors whitespace-nowrap flex-shrink-0 ${
              filterStatus === 'inactive'
                ? 'bg-primary-500 text-white'
                : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
            }`}
          >
            Inactive ({barbers.filter(b => !b.isActive).length})
          </button>
        </div>
      </div>

      {/* Barbers List */}
      {filteredBarbers.length === 0 ? (
        <Card className="text-center py-8 sm:py-12">
          <Users className="w-10 h-10 sm:w-12 sm:h-12 text-gray-300 mx-auto mb-3 sm:mb-4" />
          <p className="text-gray-500 text-sm sm:text-base">No barbers found matching your criteria</p>
        </Card>
      ) : (
        <div className="space-y-3">
          {filteredBarbers.map((barber) => (
            <Card key={barber.id} className="p-3 sm:p-5">
              <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-3 sm:gap-4">
                <div className="flex-1">
                  {/* Header Row */}
                  <div className="flex flex-wrap items-center gap-2 mb-2">
                    <h4 className="text-base sm:text-lg font-semibold text-gray-900">{barber.name}</h4>
                    <span className={`px-2 py-0.5 sm:py-1 rounded-full text-xs font-medium ${
                      barber.isActive
                        ? 'bg-green-100 text-green-700'
                        : 'bg-gray-100 text-gray-700'
                    }`}>
                      {barber.isActive ? 'Active' : 'Inactive'}
                    </span>
                    {barber.avgRating >= 4.8 && (
                      <span className="px-2 py-0.5 sm:py-1 rounded-full text-xs font-medium bg-yellow-100 text-yellow-700">
                        ⭐ Top Rated
                      </span>
                    )}
                  </div>

                  {/* Contact Info */}
                  <div className="space-y-1 sm:grid sm:grid-cols-2 sm:gap-2 sm:space-y-0 mb-3 text-xs sm:text-sm text-gray-600">
                    <div className="flex items-center gap-1.5 sm:gap-2 truncate">
                      <span className="font-medium">Email:</span>
                      <a href={`mailto:${barber.email}`} className="text-primary-600 hover:underline truncate">
                        {barber.email}
                      </a>
                    </div>
                    {barber.instagramHandle && (
                      <div className="flex items-center gap-1.5 sm:gap-2">
                        <span className="font-medium">IG:</span>
                        <a
                          href={`https://www.instagram.com/${barber.instagramHandle}/`}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="text-primary-600 hover:underline"
                        >
                          @{barber.instagramHandle}
                        </a>
                      </div>
                    )}
                  </div>
                </div>

                {/* Actions - Full width on mobile */}
                <div className="flex sm:flex-col gap-2 sm:ml-4">
                  <Button 
                    variant="outline" 
                    size="sm"
                    onClick={() => setSelectedBarberId(barber.id)}
                    className="flex-1 sm:flex-none text-xs sm:text-sm"
                  >
                    View Profile
                  </Button>
                  <Button 
                    variant="outline" 
                    size="sm"
                    onClick={() => window.location.href = `mailto:${barber.email}`}
                    className="flex-1 sm:flex-none text-xs sm:text-sm"
                  >
                    Contact
                  </Button>
                </div>
              </div>
            </Card>
          ))}
        </div>
      )}

      {/* Info Card */}
      <Card className="p-4 sm:p-6 bg-blue-50 border-blue-200">
        <div className="flex gap-2 sm:gap-3">
          <FileText className="w-4 h-4 sm:w-5 sm:h-5 text-blue-600 flex-shrink-0 mt-0.5" />
          <div>
            <h4 className="font-semibold text-blue-900 mb-1.5 sm:mb-2 text-sm sm:text-base">Campus Manager Responsibilities</h4>
            <ul className="text-xs sm:text-sm text-blue-800 space-y-1 sm:space-y-1.5">
              <li>• Monitor barber performance and assist with onboarding</li>
              <li>• Provide support and answer questions from barbers</li>
              <li>• Help resolve issues between barbers and customers</li>
              <li>• Ensure all barbers maintain professional standards</li>
              <li>• Cannot manipulate rankings, pricing, or visibility</li>
            </ul>
          </div>
        </div>
      </Card>

      {/* Barber Profile Modal */}
      {selectedBarberId && (
        <CampusManagerBarberView
          barberId={selectedBarberId}
          onClose={() => setSelectedBarberId(null)}
        />
      )}
    </div>
  );
};

// ═══════════════════════════════════════════════════════════════
// CONTENT MANAGEMENT PANEL (Instagram Integration)
// ═══════════════════════════════════════════════════════════════

const ContentManagementPanel: React.FC<{ campusId: string }> = ({ campusId }) => {
  // Map campus IDs to Instagram handles
  const getCampusInstagram = (campusId: string): string => {
    // TODO: Fetch from database/API
    const instagramHandles: Record<string, string> = {
      'campus-1': 'campuscutsslo',
      '00000000-0000-0000-0000-000000000001': 'campuscutsslo',
      // Add more campus-to-instagram mappings here
    };
    
    return instagramHandles[campusId] || 'campuscutsslo'; // Default to SLO
  };

  const instagramHandle = getCampusInstagram(campusId);
  const instagramUrl = `https://www.instagram.com/${instagramHandle}/`;

  const openInstagram = () => {
    window.open(instagramUrl, '_blank', 'noopener,noreferrer');
  };

  return (
    <div className="space-y-4 sm:space-y-6">
      <div>
        <h3 className="text-base sm:text-lg font-semibold text-gray-900 mb-1">Campus Content & Social Media</h3>
        <p className="text-xs sm:text-sm text-gray-500">
          Manage your campus's Instagram presence and share barber content with the community.
        </p>
      </div>

      {/* Instagram Card */}
      <Card className="p-5 sm:p-8">
        <div className="text-center">
          {/* Instagram Logo */}
          <div className="w-16 h-16 sm:w-20 sm:h-20 mx-auto mb-3 sm:mb-4 rounded-2xl bg-gradient-to-br from-purple-600 via-pink-600 to-orange-500 flex items-center justify-center">
            <svg className="w-9 h-9 sm:w-12 sm:h-12 text-white" fill="currentColor" viewBox="0 0 24 24">
              <path d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zm0-2.163c-3.259 0-3.667.014-4.947.072-4.358.2-6.78 2.618-6.98 6.98-.059 1.281-.073 1.689-.073 4.948 0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98 1.281.058 1.689.072 4.948.072 3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98-1.281-.059-1.69-.073-4.949-.073zm0 5.838c-3.403 0-6.162 2.759-6.162 6.162s2.759 6.163 6.162 6.163 6.162-2.759 6.162-6.163c0-3.403-2.759-6.162-6.162-6.162zm0 10.162c-2.209 0-4-1.79-4-4 0-2.209 1.791-4 4-4s4 1.791 4 4c0 2.21-1.791 4-4 4zm6.406-11.845c-.796 0-1.441.645-1.441 1.44s.645 1.44 1.441 1.44c.795 0 1.439-.645 1.439-1.44s-.644-1.44-1.439-1.44z"/>
            </svg>
          </div>

          {/* Instagram Info */}
          <h4 className="text-lg sm:text-xl font-bold text-gray-900 mb-2">
            Campus Instagram
          </h4>
          <p className="text-base sm:text-lg text-gray-700 mb-1">
            @{instagramHandle}
          </p>
          <p className="text-xs sm:text-sm text-gray-500 mb-4 sm:mb-6 max-w-md mx-auto">
            Post barber showcases, campus events, promotions, and student success stories to your campus Instagram page.
          </p>

          {/* Action Buttons */}
          <div className="flex flex-col sm:flex-row gap-2 sm:gap-3 justify-center">
            <Button
              variant="primary"
              onClick={openInstagram}
              className="bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-700 hover:to-pink-700 text-sm sm:text-base"
            >
              <FileText className="w-4 h-4 mr-2" />
              Open Instagram
            </Button>
            <Button
              variant="outline"
              onClick={() => {
                navigator.clipboard.writeText(instagramUrl);
                alert('Instagram link copied to clipboard!');
              }}
              className="text-sm sm:text-base"
            >
              Copy Link
            </Button>
          </div>
        </div>
      </Card>

      {/* Content Guidelines */}
      <Card className="p-4 sm:p-6 bg-blue-50 border-blue-200">
        <div className="flex gap-2 sm:gap-3">
          <FileText className="w-4 h-4 sm:w-5 sm:h-5 text-blue-600 flex-shrink-0 mt-0.5" />
          <div>
            <h4 className="font-semibold text-blue-900 mb-1.5 sm:mb-2 text-sm sm:text-base">Content Guidelines</h4>
            <ul className="text-xs sm:text-sm text-blue-800 space-y-1 sm:space-y-1.5">
              <li>• Showcase barber work and transformations</li>
              <li>• Highlight positive customer experiences</li>
              <li>• Promote campus events and special offers</li>
              <li>• Tag barbers and customers (with permission)</li>
              <li>• Use relevant hashtags (#CampusCut, #YourCampusName)</li>
              <li>• Maintain professional and inclusive content</li>
            </ul>
          </div>
        </div>
      </Card>

      {/* Quick Stats - Will be populated with real Instagram API data */}
      {/* Stats section temporarily hidden until Instagram API integration */}
    </div>
  );
};

// ═══════════════════════════════════════════════════════════════
// INCIDENTS PANEL (Automated Review Aggregation)
// ═══════════════════════════════════════════════════════════════

const IncidentsPanel: React.FC<{ campusId: string }> = ({ campusId }) => {
  // Incidents will be populated when the review aggregation system is implemented
  const [incidents] = useState<AutoGeneratedIncident[]>([]);
  const [selectedIncident, setSelectedIncident] = useState<AutoGeneratedIncident | null>(null);

  const getSeverityColor = (severity: string) => {
    switch (severity) {
      case 'critical': return 'bg-red-100 text-red-700 border-red-300';
      case 'high': return 'bg-orange-100 text-orange-700 border-orange-300';
      case 'medium': return 'bg-yellow-100 text-yellow-700 border-yellow-300';
      case 'low': return 'bg-blue-100 text-blue-700 border-blue-300';
      default: return 'bg-gray-100 text-gray-700 border-gray-300';
    }
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'pending_review': return 'bg-yellow-100 text-yellow-700';
      case 'acknowledged': return 'bg-blue-100 text-blue-700';
      case 'escalated': return 'bg-red-100 text-red-700';
      case 'resolved': return 'bg-green-100 text-green-700';
      default: return 'bg-gray-100 text-gray-700';
    }
  };

  const handleAcknowledge = (incidentId: string) => {
    console.log(`Acknowledging incident ${incidentId}`);
    // TODO: Update status via API
    alert('Incident acknowledged. You can now add notes and work with the barber.');
  };

  const handleEscalate = (incidentId: string) => {
    console.log(`Escalating incident ${incidentId} to admin`);
    // TODO: Escalate via API
    alert('Incident escalated to platform admin for review.');
  };

  return (
    <div className="space-y-4 sm:space-y-6">
      {/* Header */}
      <div>
        <h3 className="text-base sm:text-lg font-semibold text-gray-900 mb-1">Incident Reports</h3>
        <p className="text-xs sm:text-sm text-gray-500">
          Automatically detected from customer review patterns
        </p>
      </div>

      {/* Incidents List */}
      {incidents.length === 0 ? (
        <Card className="text-center py-8 sm:py-12">
          <CheckCircle className="w-10 h-10 sm:w-12 sm:h-12 text-green-300 mx-auto mb-3 sm:mb-4" />
          <p className="text-gray-700 font-medium text-sm sm:text-base">No incidents detected</p>
          <p className="text-xs sm:text-sm text-gray-500 mt-1">All barbers are maintaining good review patterns</p>
        </Card>
      ) : (
        <div className="space-y-4">
          {incidents.map((incident) => (
            <Card 
              key={incident.id} 
              className={`p-3 sm:p-6 border-2 ${getSeverityColor(incident.severity)}`}
            >
              {/* Header */}
              <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-3 mb-4">
                <div className="flex-1">
                  <div className="flex flex-wrap items-center gap-1.5 sm:gap-2 mb-2">
                    <h4 className="text-base sm:text-lg font-bold text-gray-900">{incident.barberName}</h4>
                    <span className={`text-[10px] sm:text-xs font-bold px-2 py-0.5 sm:py-1 rounded-full ${getSeverityColor(incident.severity)}`}>
                      {incident.severity.toUpperCase()}
                    </span>
                    <span className={`text-[10px] sm:text-xs font-medium px-2 py-0.5 sm:py-1 rounded-full ${getStatusColor(incident.status)}`}>
                      {incident.status.replace('_', ' ').toUpperCase()}
                    </span>
                  </div>
                  <div className="flex flex-wrap items-center gap-2 sm:gap-4 text-xs sm:text-sm text-gray-600">
                    <span>{incident.negativeReviewCount} negative reviews</span>
                    <span className="hidden sm:inline">•</span>
                    <span>Detected {incident.detectedAt.toLocaleDateString()}</span>
                    <span className="hidden sm:inline">•</span>
                    <span className="capitalize">{incident.type} issue</span>
                  </div>
                </div>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => setSelectedIncident(incident)}
                  className="w-full sm:w-auto text-xs sm:text-sm"
                >
                  View Details
                </Button>
              </div>

              {/* Pattern Summary */}
              <div className="mb-3 sm:mb-4 p-3 sm:p-4 bg-white rounded-lg border border-gray-200">
                <h5 className="font-semibold text-gray-900 mb-1.5 sm:mb-2 flex items-center gap-2 text-sm sm:text-base">
                  <TrendingUp className="w-3.5 h-3.5 sm:w-4 sm:h-4" />
                  Pattern Summary
                </h5>
                <p className="text-xs sm:text-sm text-gray-700">{incident.summary}</p>
              </div>

              {/* Recommendations */}
              <div className="mb-3 sm:mb-4 p-3 sm:p-4 bg-green-50 rounded-lg border border-green-200">
                <h5 className="font-semibold text-green-900 mb-1.5 sm:mb-2 text-sm sm:text-base">Recommended Actions</h5>
                <p className="text-xs sm:text-sm text-green-800">{incident.recommendation}</p>
              </div>

              {/* Actions */}
              <div className="flex flex-col sm:flex-row gap-2 sm:gap-3 sm:justify-end">
                {incident.status === 'pending_review' && (
                  <>
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => handleAcknowledge(incident.id)}
                      className="text-xs sm:text-sm"
                    >
                      <CheckCircle className="w-3.5 h-3.5 sm:w-4 sm:h-4 mr-1" />
                      Acknowledge
                    </Button>
                    <Button
                      variant="primary"
                      size="sm"
                      onClick={() => handleEscalate(incident.id)}
                      className="text-xs sm:text-sm"
                    >
                      <AlertTriangle className="w-3.5 h-3.5 sm:w-4 sm:h-4 mr-1" />
                      Escalate to Admin
                    </Button>
                  </>
                )}
                {incident.status === 'acknowledged' && (
                  <Button
                    variant="primary"
                    size="sm"
                    onClick={() => handleEscalate(incident.id)}
                    className="text-xs sm:text-sm"
                  >
                    <AlertTriangle className="w-3.5 h-3.5 sm:w-4 sm:h-4 mr-1" />
                    Escalate to Admin
                  </Button>
                )}
                {incident.status === 'escalated' && (
                  <span className="text-xs sm:text-sm text-gray-600 italic text-center sm:text-right">
                    Escalated to admin - awaiting resolution
                  </span>
                )}
              </div>
            </Card>
          ))}
        </div>
      )}

      {/* Incident Details Modal */}
      {selectedIncident && (
        <IncidentDetailsModal
          incident={selectedIncident}
          onClose={() => setSelectedIncident(null)}
        />
      )}
    </div>
  );
};

