/**
 * Campus Manager Dashboard
 * 
 * Conditional overlay shown only when barber.isCampusManager === true
 * Reuses 100% of existing Barber page styles and layout
 */

import React, { useState, useEffect } from 'react';
import { 
  Users, 
  TrendingUp, 
  AlertTriangle,
  CheckCircle,
  XCircle,
  Clock,
  Flag,
  RefreshCw
} from 'lucide-react';
import Card from './Card';
import Button from './Button';
import { CampusManagerBarberView } from './CampusManagerBarberView';
import barberApplicationService, { BarberApplication } from '../services/barber-application.service';
import toast from 'react-hot-toast';

interface Incident {
  id: string;
  barberName: string;
  type: string;
  description: string;
  status: 'open' | 'escalated' | 'resolved';
  createdAt: Date;
}

// Automated review aggregation interfaces
interface NegativeReview {
  reviewId: string;
  customerName: string;
  rating: number;
  comment: string;
  createdAt: Date;
  sentiment: 'negative' | 'very_negative';
  analysis: string;
}

interface AutoGeneratedIncident {
  id: string;
  barberId: string;
  barberName: string;
  barberEmail: string;
  type: 'quality' | 'professionalism' | 'safety' | 'other';
  severity: 'low' | 'medium' | 'high' | 'critical';
  negativeReviewCount: number;
  negativeReviews: NegativeReview[];
  summary: string;
  recommendation: string;
  detectedAt: Date;
  status: 'pending_review' | 'acknowledged' | 'escalated' | 'resolved';
  campusManagerNotes?: string;
}

interface CampusManagerDashboardProps {
  campusId: string;
  campusName: string;
}

// ═══════════════════════════════════════════════════════════════
// INCIDENT DETAILS MODAL
// ═══════════════════════════════════════════════════════════════

const IncidentDetailsModal: React.FC<{ 
  incident: AutoGeneratedIncident; 
  onClose: () => void 
}> = ({ incident, onClose }) => {
  return (
    <div 
      className="fixed inset-0 min-h-[100dvh] bg-black bg-opacity-50 flex items-center justify-center z-[60] p-2 sm:p-4"
      onClick={onClose}
    >
      <div 
        className="bg-white rounded-lg shadow-xl max-w-4xl w-full max-h-[85dvh] sm:max-h-[90vh] overflow-y-auto"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="sticky top-0 bg-white border-b border-gray-200 px-4 sm:px-6 py-3 sm:py-4 flex items-center justify-between z-10">
          <div>
            <h2 className="text-base sm:text-xl font-bold text-gray-900">Incident Report Details</h2>
            <p className="text-xs sm:text-sm text-gray-500">Automatically generated from review patterns</p>
          </div>
          <button
            onClick={onClose}
            className="text-gray-400 hover:text-gray-600 text-2xl leading-none p-1"
          >
            ×
          </button>
        </div>

        {/* Content */}
        <div className="p-4 sm:p-6 space-y-4 sm:space-y-6">
          {/* Barber Info */}
          <Card className="p-4 sm:p-6">
            <h3 className="font-semibold text-gray-900 mb-3 sm:mb-4 text-sm sm:text-base">Barber Information</h3>
            <div className="grid grid-cols-2 gap-3 sm:gap-4 text-xs sm:text-sm">
              <div>
                <p className="text-gray-600">Name</p>
                <p className="font-medium text-gray-900">{incident.barberName}</p>
              </div>
              <div>
                <p className="text-gray-600">Email</p>
                <p className="font-medium text-gray-900 truncate">{incident.barberEmail}</p>
              </div>
              <div>
                <p className="text-gray-600">Issue Type</p>
                <p className="font-medium text-gray-900 capitalize">{incident.type}</p>
              </div>
              <div>
                <p className="text-gray-600">Severity</p>
                <p className="font-medium text-gray-900 capitalize">{incident.severity}</p>
              </div>
              <div>
                <p className="text-gray-600">Negative Reviews</p>
                <p className="font-medium text-gray-900">{incident.negativeReviewCount}</p>
              </div>
              <div>
                <p className="text-gray-600">Detected</p>
                <p className="font-medium text-gray-900">{incident.detectedAt.toLocaleDateString()}</p>
              </div>
            </div>
          </Card>

          {/* Pattern Analysis */}
          <Card className="p-4 sm:p-6 bg-blue-50 border-blue-200">
            <h3 className="font-semibold text-blue-900 mb-2 sm:mb-3 flex items-center gap-2 text-sm sm:text-base">
              <TrendingUp className="w-4 h-4 sm:w-5 sm:h-5" />
              Pattern Analysis
            </h3>
            <p className="text-xs sm:text-sm text-blue-800 leading-relaxed">{incident.summary}</p>
          </Card>

          {/* Recommendations */}
          <Card className="p-4 sm:p-6 bg-green-50 border-green-200">
            <h3 className="font-semibold text-green-900 mb-2 sm:mb-3 text-sm sm:text-base">Recommended Actions</h3>
            <p className="text-xs sm:text-sm text-green-800 leading-relaxed">{incident.recommendation}</p>
          </Card>

          {/* Individual Reviews */}
          <div>
            <h3 className="font-semibold text-gray-900 mb-3 sm:mb-4 text-sm sm:text-base">Negative Reviews ({incident.negativeReviews.length})</h3>
            <div className="space-y-3 sm:space-y-4">
              {incident.negativeReviews.map((review) => (
                <Card 
                  key={review.reviewId} 
                  className={`p-3 sm:p-5 ${
                    review.sentiment === 'very_negative' 
                      ? 'border-2 border-red-300 bg-red-50' 
                      : 'border border-gray-200'
                  }`}
                >
                  <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between mb-2 sm:mb-3 gap-2">
                    <div className="flex-1">
                      <div className="flex flex-wrap items-center gap-2 mb-1.5 sm:mb-2">
                        <span className="font-medium text-gray-900 text-sm sm:text-base">{review.customerName}</span>
                        <span className={`text-[10px] sm:text-xs font-bold px-1.5 sm:px-2 py-0.5 sm:py-1 rounded-full ${
                          review.sentiment === 'very_negative'
                            ? 'bg-red-100 text-red-700'
                            : 'bg-yellow-100 text-yellow-700'
                        }`}>
                          {review.sentiment.replace('_', ' ').toUpperCase()}
                        </span>
                      </div>
                      <div className="flex items-center gap-1 mb-1.5 sm:mb-2">
                        {[...Array(5)].map((_, i) => (
                          <span
                            key={i}
                            className={`text-sm sm:text-base ${i < review.rating ? 'text-yellow-400' : 'text-gray-300'}`}
                          >
                            ★
                          </span>
                        ))}
                        <span className="text-xs sm:text-sm text-gray-600 ml-2">
                          {review.createdAt.toLocaleDateString()}
                        </span>
                      </div>
                    </div>
                  </div>
                  
                  <div className="mb-2 sm:mb-3">
                    <p className="text-xs sm:text-sm text-gray-700 italic">"{review.comment}"</p>
                  </div>

                  <div className="p-2 sm:p-3 bg-white rounded-lg border border-gray-200">
                    <p className="text-[10px] sm:text-xs font-semibold text-gray-700 mb-0.5 sm:mb-1">Analysis:</p>
                    <p className="text-[10px] sm:text-xs text-gray-600">{review.analysis}</p>
                  </div>
                </Card>
              ))}
            </div>
          </div>

          {/* Actions */}
          <div className="flex flex-col sm:flex-row gap-2 sm:gap-3 sm:justify-end pt-4 border-t border-gray-200">
            <Button variant="outline" onClick={onClose} className="text-sm sm:text-base order-2 sm:order-1">
              Close
            </Button>
            <Button variant="primary" className="text-sm sm:text-base order-1 sm:order-2">
              <AlertTriangle className="w-4 h-4 mr-2" />
              Escalate to Admin
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
};

export const CampusManagerDashboard: React.FC<CampusManagerDashboardProps> = ({ 
  campusId, 
  campusName 
}) => {
  const [activeTab, setActiveTab] = useState<'applications' | 'barbers' | 'bookings'>('applications');
  const [isTransitioning, setIsTransitioning] = useState(false);
  const [displayedTab, setDisplayedTab] = useState(activeTab);

  const handleTabChange = (newTab: typeof activeTab) => {
    if (newTab === activeTab) return;
    setIsTransitioning(true);
    setTimeout(() => {
      setDisplayedTab(newTab);
      setActiveTab(newTab);
      setTimeout(() => {
        setIsTransitioning(false);
      }, 20);
    }, 150);
  };

  return (
    <div className="space-y-4 sm:space-y-6">
      {/* Tab Navigation - Scrollable on mobile */}
      <div className="border-b border-gray-200 -mx-4 sm:mx-0 px-4 sm:px-0">
        <nav className="flex gap-1 sm:gap-6 overflow-x-auto pb-px scrollbar-hide">
          <button
            onClick={() => handleTabChange('applications')}
            className={`py-3 sm:py-4 px-3 sm:px-2 border-b-2 font-medium text-xs sm:text-sm transition-all duration-200 whitespace-nowrap flex-shrink-0 ${
              activeTab === 'applications'
                ? 'border-primary-500 text-primary-600'
                : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
            }`}
          >
            <div className="flex items-center gap-1.5 sm:gap-2">
              <Users className="w-4 h-4" />
              <span className="hidden sm:inline">Barber </span>Applications
            </div>
          </button>
          
          <button
            onClick={() => handleTabChange('barbers')}
            className={`py-3 sm:py-4 px-3 sm:px-2 border-b-2 font-medium text-xs sm:text-sm transition-all duration-200 whitespace-nowrap flex-shrink-0 ${
              activeTab === 'barbers'
                ? 'border-primary-500 text-primary-600'
                : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
            }`}
          >
            <div className="flex items-center gap-1.5 sm:gap-2">
              <Users className="w-4 h-4" />
              <span className="hidden sm:inline">Barber </span>Management
            </div>
          </button>
          
          <button
            onClick={() => handleTabChange('bookings')}
            className={`py-3 sm:py-4 px-3 sm:px-2 border-b-2 font-medium text-xs sm:text-sm transition-all duration-200 whitespace-nowrap flex-shrink-0 ${
              activeTab === 'bookings'
                ? 'border-primary-500 text-primary-600'
                : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
            }`}
          >
            <div className="flex items-center gap-1.5 sm:gap-2">
              <CheckCircle className="w-4 h-4" />
              Bookings
            </div>
          </button>
        </nav>
      </div>

      {/* Tab Content with smooth transition */}
      {/* Key on campusId forces re-mount and data refresh when campus changes */}
      <div 
        key={campusId}
        className={`transition-all duration-150 ease-out ${
          isTransitioning 
            ? 'opacity-0 translate-y-2' 
            : 'opacity-100 translate-y-0'
        }`}
      >
        {displayedTab === 'applications' && <BarberApplicationsPanel campusId={campusId} />}
        {displayedTab === 'barbers' && <BarberManagementPanel campusId={campusId} campusName={campusName} />}
        {displayedTab === 'bookings' && <CompletedBookingsPanel campusId={campusId} />}
      </div>
    </div>
  );
};

// ═══════════════════════════════════════════════════════════════
// BARBER APPLICATIONS PANEL
// ═══════════════════════════════════════════════════════════════

const BarberApplicationsPanel: React.FC<{ campusId: string }> = ({ campusId }) => {
  const [applications, setApplications] = useState<BarberApplication[]>([]);
  const [loading, setLoading] = useState(true);
  const [actionLoading, setActionLoading] = useState<string | null>(null);

  const fetchApplications = async () => {
    try {
      setLoading(true);
      // Pass campusId to filter applications by the selected campus
      const applications = await barberApplicationService.getAllApplications(campusId);
      setApplications(applications);
    } catch (error) {
      console.error('Failed to fetch applications:', error);
      toast.error('Failed to load barber applications');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchApplications();
  }, [campusId]); // Re-fetch when campusId changes

  const handleAction = async (applicationId: string, action: 'approve' | 'reject' | 'interview') => {
    try {
      setActionLoading(applicationId);
      const statusMap = {
        'approve': 'approved' as const,
        'reject': 'rejected' as const,
        'interview': 'interview_scheduled' as const,
      };
      
      await barberApplicationService.updateApplicationStatus(applicationId, statusMap[action]);
      toast.success(`Application ${action === 'interview' ? 'scheduled for interview' : action + 'd'} successfully`);
      fetchApplications(); // Refresh the list
    } catch (error) {
      console.error(`Failed to ${action} application:`, error);
      toast.error(`Failed to ${action} application`);
    } finally {
      setActionLoading(null);
    }
  };

  const getStatusStyle = (status: string) => {
    switch (status) {
      case 'pending': return 'bg-yellow-100 text-yellow-700';
      case 'under_review': return 'bg-blue-100 text-blue-700';
      case 'interview_scheduled': return 'bg-purple-100 text-purple-700';
      case 'approved': return 'bg-green-100 text-green-700';
      case 'rejected': return 'bg-red-100 text-red-700';
      default: return 'bg-gray-100 text-gray-700';
    }
  };

  const formatStatus = (status: string) => {
    return status.split('_').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(' ');
  };

  if (loading) {
    return (
      <div className="space-y-4">
        <Card className="text-center py-8 sm:py-12">
          <RefreshCw className="w-8 h-8 text-gray-400 mx-auto mb-3 animate-spin" />
          <p className="text-gray-500 text-sm sm:text-base">Loading applications...</p>
        </Card>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      {applications.length === 0 ? (
        <Card className="text-center py-8 sm:py-12">
          <Users className="w-10 h-10 sm:w-12 sm:h-12 text-gray-300 mx-auto mb-3 sm:mb-4" />
          <p className="text-gray-500 text-sm sm:text-base">No barber applications yet</p>
        </Card>
      ) : (
        <div className="space-y-3">
          {applications.map((app) => (
            <Card key={app.id} className="p-3 sm:p-4">
              <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-3">
                <div className="flex-1">
                  <h4 className="font-semibold text-gray-900 text-base sm:text-lg">
                    {app.first_name || app.user?.first_name || 'Unknown'} {app.last_name || app.user?.last_name || 'User'}
                  </h4>
                  <p className="text-sm text-gray-600 mt-1">{app.email || app.user?.email || 'No email'}</p>
                  <div className="flex flex-wrap items-center gap-2 sm:gap-4 mt-2">
                    <span className="text-xs text-gray-500">
                      Applied {new Date(app.created_at).toLocaleDateString()}
                    </span>
                    {app.years_experience && (
                      <span className="text-xs text-gray-500">
                        {app.years_experience} years exp.
                      </span>
                    )}
                  </div>
                  {app.why_be_barber && (
                    <p className="text-xs text-gray-600 mt-2 line-clamp-2">
                      "{app.why_be_barber}"
                    </p>
                  )}
                </div>
                
                {/* Buttons - Grid on mobile, flex on desktop */}
                <div className="grid grid-cols-2 sm:flex gap-2 sm:ml-4">
                  {app.status === 'pending' && (
                    <>
                      <Button
                        variant="primary"
                        size="sm"
                        onClick={() => handleAction(app.id, 'approve')}
                        disabled={actionLoading === app.id}
                        className="text-xs sm:text-sm"
                      >
                        <CheckCircle className="w-3.5 h-3.5 sm:w-4 sm:h-4 mr-1" />
                        Approve
                      </Button>
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => handleAction(app.id, 'reject')}
                        disabled={actionLoading === app.id}
                        className="text-red-600 border-red-300 hover:bg-red-50 text-xs sm:text-sm col-span-2 sm:col-span-1"
                      >
                        <XCircle className="w-3.5 h-3.5 sm:w-4 sm:h-4 mr-1" />
                        Reject
                      </Button>
                    </>
                  )}
                  {(app.status === 'under_review' || app.status === 'interview_scheduled') && (
                    <>
                      <Button
                        variant="primary"
                        size="sm"
                        onClick={() => handleAction(app.id, 'approve')}
                        disabled={actionLoading === app.id}
                        className="text-xs sm:text-sm"
                      >
                        <CheckCircle className="w-3.5 h-3.5 sm:w-4 sm:h-4 mr-1" />
                        Approve
                      </Button>
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => handleAction(app.id, 'reject')}
                        disabled={actionLoading === app.id}
                        className="text-red-600 border-red-300 hover:bg-red-50 text-xs sm:text-sm"
                      >
                        <XCircle className="w-3.5 h-3.5 sm:w-4 sm:h-4 mr-1" />
                        Reject
                      </Button>
                    </>
                  )}
                  {app.status === 'approved' && (
                    <span className="text-xs text-green-600 font-medium flex items-center gap-1">
                      <CheckCircle className="w-4 h-4" />
                      Approved
                    </span>
                  )}
                  {app.status === 'rejected' && (
                    <span className="text-xs text-red-600 font-medium flex items-center gap-1">
                      <XCircle className="w-4 h-4" />
                      Rejected
                    </span>
                  )}
                </div>
              </div>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
};

// ═══════════════════════════════════════════════════════════════
// BARBER MANAGEMENT PANEL
// ═══════════════════════════════════════════════════════════════

interface CampusBarber {
  id: string;
  name: string;
  email: string;
  avgRating: number;
  totalBookings: number;
  completedBookings: number;
  isActive: boolean;
}

const BarberManagementPanel: React.FC<{ campusId: string; campusName: string }> = ({ campusId, campusName }) => {
  const [barbers, setBarbers] = useState<CampusBarber[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedBarberId, setSelectedBarberId] = useState<string | null>(null);

  const fetchBarbers = async () => {
    try {
      setLoading(true);
      const barberServiceModule = await import('../services/barber.service');
      const barberService = barberServiceModule.default;
      // Filter by campusId to only show barbers for this campus
      // Note: Backend expects camelCase 'campusId' parameter
      const response = await barberService.getBarbers({ campusId } as any);
      
      // Extract barbers array from response - handle both paginated and direct array responses
      const barbersArray = Array.isArray(response) ? response : (response?.data || []);
      
      // Map API response to CampusBarber format
      const mappedBarbers: CampusBarber[] = barbersArray.map((barber: any) => ({
        id: barber.id,
        name: barber.name || barber.display_name || `${barber.first_name || ''} ${barber.last_name || ''}`.trim() || 'Unknown',
        email: barber.email || barber.user?.email || '',
        avgRating: barber.average_rating || 0,
        totalBookings: barber.total_bookings || 0,
        completedBookings: barber.completed_bookings || barber.total_bookings || 0,
        isActive: barber.is_active !== false,
      }));
      
      setBarbers(mappedBarbers);
    } catch (error) {
      console.error('Failed to fetch barbers:', error);
      toast.error('Failed to load barbers');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchBarbers();
  }, [campusId]); // Re-fetch when campusId changes

  // Filter barbers based on search
  const filteredBarbers = barbers.filter((barber) => {
    return barber.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
           barber.email.toLowerCase().includes(searchQuery.toLowerCase());
  });

  if (loading) {
    return (
      <div className="space-y-4">
        <Card className="text-center py-8 sm:py-12">
          <RefreshCw className="w-8 h-8 text-gray-400 mx-auto mb-3 animate-spin" />
          <p className="text-gray-500 text-sm sm:text-base">Loading barbers...</p>
        </Card>
      </div>
    );
  }

  // If a barber is selected, show their profile instead of the list
  if (selectedBarberId) {
    return (
      <CampusManagerBarberView
        barberId={selectedBarberId}
        onClose={() => setSelectedBarberId(null)}
      />
    );
  }

  return (
    <div className="space-y-4 sm:space-y-6">
      {/* Search */}
      <div>
        <input
          type="text"
          placeholder="Search by name or email..."
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
          className="w-full pl-4 pr-4 py-2.5 sm:py-2 text-sm border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-400 focus:border-transparent"
        />
      </div>

      {/* Barbers List */}
      {filteredBarbers.length === 0 ? (
        <Card className="text-center py-8 sm:py-12">
          <Users className="w-10 h-10 sm:w-12 sm:h-12 text-gray-300 mx-auto mb-3 sm:mb-4" />
          <p className="text-gray-500 text-sm sm:text-base">No barbers found matching your criteria</p>
        </Card>
      ) : (
        <div className="space-y-3">
          {filteredBarbers.map((barber) => (
            <Card key={barber.id} className="p-3 sm:p-5">
              <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-3 sm:gap-4">
                <div className="flex-1">
                  {/* Header Row */}
                  <div className="flex flex-wrap items-center gap-2 mb-2">
                    <h4 className="text-base sm:text-lg font-semibold text-gray-900">{barber.name}</h4>
                  </div>

                  {/* Contact Info */}
                  <div className="mb-3 text-xs sm:text-sm text-gray-600">
                    <div className="flex items-center gap-1.5 sm:gap-2 truncate">
                      <span className="font-medium">Email:</span>
                      <a href={`mailto:${barber.email}`} className="text-primary-600 hover:underline truncate">
                        {barber.email}
                      </a>
                    </div>
                  </div>
                </div>

                {/* Actions - Full width on mobile */}
                <div className="flex sm:flex-col gap-2 sm:ml-4">
                  <Button 
                    variant="outline" 
                    size="sm"
                    onClick={() => setSelectedBarberId(barber.id)}
                    className="flex-1 sm:flex-none text-xs sm:text-sm"
                  >
                    View Profile
                  </Button>
                  <Button 
                    variant="outline" 
                    size="sm"
                    onClick={() => window.location.href = `mailto:${barber.email}`}
                    className="flex-1 sm:flex-none text-xs sm:text-sm"
                  >
                    Contact
                  </Button>
                </div>
              </div>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
};

// ═══════════════════════════════════════════════════════════════
// COMPLETED BOOKINGS PANEL
// ═══════════════════════════════════════════════════════════════

interface CompletedBooking {
  id: string;
  barberId: string;
  barberRecordId: string;
  barberName: string;
  barberAvatar: string | null;
  consumerName: string;
  consumerAvatar: string | null;
  serviceType: string;
  priceUsdCents: number;
  scheduledTime: string;
  paidAt: string | null;
  location: string | null;
  notes: string | null;
  review: {
    rating: number;
    comment: string | null;
    reviewedAt: string;
  } | null;
}

interface BarberOption {
  id: string;
  name: string;
}

const CompletedBookingsPanel: React.FC<{ campusId: string }> = ({ campusId }) => {
  const [bookings, setBookings] = useState<CompletedBooking[]>([]);
  const [barbers, setBarbers] = useState<BarberOption[]>([]);
  const [selectedBarberId, setSelectedBarberId] = useState<string>('all');
  const [loading, setLoading] = useState(true);

  const fetchBookings = async () => {
    try {
      setLoading(true);
      const token = localStorage.getItem('accessToken');
      const barberFilter = selectedBarberId !== 'all' ? `&barberId=${selectedBarberId}` : '';
      const response = await fetch(
        `/api/v1/bookings-simple/campus/${campusId}?limit=100${barberFilter}`,
        {
          headers: { Authorization: `Bearer ${token}` },
        }
      );
      
      if (response.ok) {
        const data = await response.json();
        setBookings(data.data.bookings || []);
        setBarbers(data.data.barbers || []);
      } else {
        console.error('Failed to fetch campus bookings:', response.status);
      }
    } catch (error) {
      console.error('Failed to fetch campus bookings:', error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchBookings();
  }, [campusId, selectedBarberId]);

  const formatDate = (dateStr: string) => {
    return new Date(dateStr).toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
      hour: 'numeric',
      minute: '2-digit',
    });
  };

  const formatPrice = (cents: number) => `$${(cents / 100).toFixed(2)}`;

  const renderStars = (rating: number) => {
    return (
      <div className="flex items-center gap-0.5">
        {[1, 2, 3, 4, 5].map((star) => (
          <span
            key={star}
            className={`text-sm ${star <= rating ? 'text-yellow-400' : 'text-gray-300'}`}
          >
            ★
          </span>
        ))}
      </div>
    );
  };

  // Group bookings by barber for summary
  const bookingsByBarber = bookings.reduce((acc, booking) => {
    if (!acc[booking.barberName]) {
      acc[booking.barberName] = { count: 0, totalRevenue: 0, avgRating: 0, ratings: [] as number[] };
    }
    acc[booking.barberName].count++;
    acc[booking.barberName].totalRevenue += booking.priceUsdCents;
    if (booking.review?.rating) {
      acc[booking.barberName].ratings.push(booking.review.rating);
    }
    return acc;
  }, {} as Record<string, { count: number; totalRevenue: number; avgRating: number; ratings: number[] }>);

  // Calculate averages
  Object.keys(bookingsByBarber).forEach(name => {
    const data = bookingsByBarber[name];
    data.avgRating = data.ratings.length > 0 
      ? data.ratings.reduce((a, b) => a + b, 0) / data.ratings.length 
      : 0;
  });

  if (loading) {
    return (
      <Card className="text-center py-8">
        <RefreshCw className="w-8 h-8 text-primary-400 mx-auto mb-3 animate-spin" />
        <p className="text-gray-600">Loading bookings...</p>
      </Card>
    );
  }

  return (
    <div className="space-y-4 sm:space-y-6">
      {/* Filter Bar */}
      <Card className="p-4">
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
          <div>
            <h3 className="font-semibold text-gray-900">Completed Bookings</h3>
            <p className="text-sm text-gray-500">{bookings.length} completed bookings total</p>
          </div>
          <div className="flex items-center gap-2">
            <label className="text-sm text-gray-600">Filter by barber:</label>
            <select
              value={selectedBarberId}
              onChange={(e) => setSelectedBarberId(e.target.value)}
              className="px-3 py-2 border border-gray-300 rounded-lg text-sm focus:ring-2 focus:ring-primary-400 focus:border-transparent"
            >
              <option value="all">All Barbers</option>
              {barbers.map((barber) => (
                <option key={barber.id} value={barber.id}>{barber.name}</option>
              ))}
            </select>
          </div>
        </div>
      </Card>

      {/* Summary Stats by Barber */}
      {selectedBarberId === 'all' && Object.keys(bookingsByBarber).length > 0 && (
        <Card className="p-4">
          <h4 className="font-semibold text-gray-900 mb-3 flex items-center gap-2">
            <TrendingUp className="w-4 h-4 text-primary-600" />
            Barber Performance Summary
          </h4>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
            {Object.entries(bookingsByBarber).map(([name, data]) => (
              <div 
                key={name} 
                className="p-3 bg-gray-50 rounded-lg border border-gray-200 cursor-pointer hover:bg-gray-100 transition-colors"
                onClick={() => {
                  const barber = barbers.find(b => b.name === name);
                  if (barber) setSelectedBarberId(barber.id);
                }}
              >
                <div className="font-medium text-gray-900">{name}</div>
                <div className="flex items-center justify-between mt-2 text-sm">
                  <span className="text-gray-600">{data.count} bookings</span>
                  <span className="text-green-600 font-medium">{formatPrice(data.totalRevenue)}</span>
                </div>
                {data.avgRating > 0 && (
                  <div className="flex items-center gap-1 mt-1">
                    {renderStars(Math.round(data.avgRating))}
                    <span className="text-xs text-gray-500">({data.avgRating.toFixed(1)})</span>
                  </div>
                )}
              </div>
            ))}
          </div>
        </Card>
      )}

      {/* Bookings List */}
      {bookings.length === 0 ? (
        <Card className="text-center py-8 sm:py-12">
          <Clock className="w-10 h-10 sm:w-12 sm:h-12 text-gray-300 mx-auto mb-3 sm:mb-4" />
          <p className="text-gray-700 font-medium text-sm sm:text-base">No completed bookings yet</p>
          <p className="text-xs sm:text-sm text-gray-500 mt-1">
            {selectedBarberId !== 'all' 
              ? 'This barber has no completed bookings' 
              : 'Completed bookings will appear here'}
          </p>
        </Card>
      ) : (
        <div className="space-y-3">
          {bookings.map((booking) => (
            <Card key={booking.id} className="p-4">
              <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-3">
                {/* Left side - booking info */}
                <div className="flex-1">
                  <div className="flex items-center gap-3 mb-2">
                    <div className="w-10 h-10 rounded-full bg-gray-200 flex items-center justify-center overflow-hidden">
                      {booking.barberAvatar ? (
                        <img src={booking.barberAvatar} alt="" className="w-full h-full object-cover" />
                      ) : (
                        <Users className="w-5 h-5 text-gray-400" />
                      )}
                    </div>
                    <div>
                      <p className="font-semibold text-gray-900">{booking.barberName}</p>
                      <p className="text-sm text-gray-600">{booking.serviceType}</p>
                    </div>
                  </div>
                  
                  <div className="text-sm text-gray-600 space-y-1 ml-13">
                    <p><span className="text-gray-500">Customer:</span> {booking.consumerName}</p>
                    <p><span className="text-gray-500">Date:</span> {formatDate(booking.scheduledTime)}</p>
                    {booking.location && (
                      <p><span className="text-gray-500">Location:</span> {booking.location}</p>
                    )}
                    {booking.notes && (
                      <p className="italic text-gray-500">"{booking.notes}"</p>
                    )}
                  </div>
                </div>

                {/* Right side - price and review */}
                <div className="text-right">
                  <p className="font-bold text-lg text-green-600">{formatPrice(booking.priceUsdCents)}</p>
                  {booking.paidAt && (
                    <p className="text-xs text-gray-500">Paid {formatDate(booking.paidAt)}</p>
                  )}
                  
                  {/* Review */}
                  {booking.review ? (
                    <div className="mt-2 p-2 bg-gray-50 rounded-lg">
                      {renderStars(booking.review.rating)}
                      {booking.review.comment && (
                        <p className="text-xs text-gray-600 mt-1 max-w-[200px] truncate">
                          "{booking.review.comment}"
                        </p>
                      )}
                    </div>
                  ) : (
                    <p className="text-xs text-gray-400 mt-2 italic">No review</p>
                  )}
                </div>
              </div>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
};

